version: '3.9'

services:
    db:
        image: mysql:8.0
        restart: always
        environment:
            - MYSQL_DATABASE=test
            - MYSQL_ROOT_PASSWORD=asdasd
        ports:
            - '3306:3306'
        volumes:
            - ./db:/var/lib/mysql
