version: '3.9'

services:
    api:
        container_name: api
        image: api
        build:
            context: .
            dockerfile: api.Dockerfile
        ports:
            - '8000:8000'
