version: '3.9'

services:
    app:
        container_name: app
        image: app
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        ports:
            - '8080:8080'
        volumes:
            - './app/static:/app/static'
            - './nginx.conf:/etc/nginx/nginx.conf'
    db:
        image: mysql:8.0
        cap_add:
            - SYS_NICE
        restart: always
        environment:
            - MYSQL_DATABASE=quotes
            - MYSQL_ROOT_PASSWORD=mauFJcuf5dhRMQrjj
        ports:
            - '3306:3306'
        volumes:
            - ./db:/var/lib/mysql
            - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
