openapi: 3.0.0

servers:
    - url: http://localhost:8000

paths:
    /product/list:
        post:
            summary: Returns a list of products.
            description: Optional extended description in CommonMark or HTML
            responses:
                '200':
                    description: A JSON array of product names
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    type: string

    /product/add:
        post:
            summary: Add one product.
            description: Adding product
            requestBody:
                description: New product, just the name
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                name:
                                    type: string
                            required:
                                - name
            responses:
                '200':
                    description: A JSON array of product names
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    type: string
